"""
calibrate_pick.py - build the DYNAMIC PICK model. THIS is how the robot part
actually works (no ArUco, no printed markers).

The idea, plain and simple:
  "wherever the piece is, drive the robot there, save the joints, and train."

For several pieces you: let YOLO see the piece -> get its position -> jog the
robot tip onto it -> record the 6 joint angles. From those samples we build
pick_model.json, which later interpolates the joints for ANY new piece position
(inverse-distance weighting). The camera-pixel -> table-mm mapping
(homography.npy) is used only to give each piece a stable coordinate.

Flow
----
  1. Put a piece on the belt -> the script shows its current position.
  2. Press SPACE to capture it.
  3. Jog the robot tip onto that piece; the script reads /robot2/joint_states.
  4. Repeat for >= 6 pieces spread across the reachable area.
  5. Press Q -> writes calib_pairs.json + pick_model.json (and refreshes homography.npy).

Requires ROS 2 sourced (for the joint_states read).
"""
import sys
import json
import re
import subprocess
from pathlib import Path

import cv2
import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from config import (CAMERA_ID, FRAME_W, FRAME_H, HOMOGRAPHY_FILE,
                    YOLO_MODEL_PATH, PICK_MODEL_FILE, CALIB_FILE)
from homography_utils import load_homography, pixel_to_robot

try:
    from ultralytics import YOLO
except ImportError:
    print("ERROR: pip install ultralytics"); raise SystemExit(1)

CONF_THR = 0.35
WIN = "Calibration | SPACE=capture | Q=finish and calibrate"

# Reference pick->prepick joint delta (joint indices 1..5), from known poses.
DELTA_PREPICK = [0.1666, 0.0303, -0.0629, -0.1841, -0.5922]

_JOINT_RE = re.compile(r"^-\s+([-+]?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?)$")


def ask_joints():
    """Read 6 joint values from /robot2/joint_states, or fall back to manual paste."""
    input("  Move the robot onto the piece, then press ENTER...")
    print("  Reading joints automatically...", end="", flush=True)
    try:
        out = subprocess.run(
            "source /opt/ros/jazzy/setup.bash && ros2 topic echo --once /robot2/joint_states",
            shell=True, executable="/bin/bash",
            capture_output=True, text=True, timeout=10)
        raw = out.stdout + out.stderr
    except subprocess.TimeoutExpired:
        print(" TIMEOUT"); return _ask_joints_manual()

    in_position, values = False, []
    for line in raw.splitlines():
        s = line.strip()
        if s == "position:":
            in_position = True
            continue
        if in_position:
            m = _JOINT_RE.match(s)
            if m:
                values.append(float(m.group(1)))
                if len(values) == 6:
                    break
            elif s and not s.startswith("#"):
                in_position = False
    if len(values) == 6:
        print(" OK", [round(v, 4) for v in values])
        return values
    print(f" ERROR ({len(values)} values)")
    return _ask_joints_manual()


def _ask_joints_manual():
    print("  Paste the output of: ros2 topic echo /robot2/joint_states --once")
    print("  (empty ENTER to finish):")
    lines = []
    while True:
        line = input("> ")
        if line.strip() == "" and lines:
            break
        if line.strip():
            lines.append(line.strip())
    vals = [float(_JOINT_RE.match(l).group(1)) for l in lines if _JOINT_RE.match(l)]
    values = vals[:6]
    if len(values) == 6:
        return values
    print(f"  [!] {len(values)} values, need 6. Retry.")
    return _ask_joints_manual()


def build_pick_model(robot_pts, joints_list):
    points = [{"x_mm": round(x, 2), "y_mm": round(y, 2), "pick_joints": j}
              for (x, y), j in zip(robot_pts, joints_list)]
    data = {"comment": "Generated by calibrate_pick.py",
            "delta_prepick": DELTA_PREPICK, "points": points}
    PICK_MODEL_FILE.write_text(json.dumps(data, indent=2))
    print(f"[OK] pick_model.json updated ({len(points)} points)")


def main():
    cap = cv2.VideoCapture(CAMERA_ID, cv2.CAP_V4L2)
    cap.set(cv2.CAP_PROP_FRAME_WIDTH, FRAME_W)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, FRAME_H)
    cap.set(cv2.CAP_PROP_BUFFERSIZE, 1)

    model = YOLO(str(YOLO_MODEL_PATH))
    H_cur = load_homography(HOMOGRAPHY_FILE)

    pixel_pts, robot_pts, joints_list = [], [], []
    pending = None
    print("\n=== MULTI-POINT CALIBRATION ===")
    print("SPACE = capture visible piece | Q = finish and save\n")

    while True:
        ok, frame = cap.read()
        if not ok:
            continue
        results = model(frame, conf=CONF_THR, verbose=False)
        boxes = results[0].boxes
        names = results[0].names
        vis = frame.copy()

        best, best_conf = None, 0.0
        for box in boxes:
            c = float(box.conf[0])
            if c > best_conf:
                best_conf = c
                x1, y1, x2, y2 = map(int, box.xyxy[0].tolist())
                best = ((x1+x2)//2, (y1+y2)//2, x1, y1, x2, y2,
                        names[int(box.cls[0])], c)

        if best:
            cx, cy, x1, y1, x2, y2, name, conf = best
            x_mm, y_mm = pixel_to_robot(cx, cy, H_cur)
            cv2.rectangle(vis, (x1, y1), (x2, y2), (0, 255, 80), 2)
            cv2.circle(vis, (cx, cy), 7, (0, 255, 80), -1)
            cv2.putText(vis, f"{name} {conf:.2f}", (x1, y1-10),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.55, (0, 255, 80), 2)
            cv2.putText(vis, f"({x_mm:.1f}, {y_mm:.1f}) mm", (x1, y2+20),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.65, (0, 255, 80), 2)
            pending = (cx, cy, x_mm, y_mm)

        cv2.putText(vis, f"Points: {len(pixel_pts)}", (8, 22),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 220, 255), 2)
        cv2.imshow(WIN, vis)
        key = cv2.waitKey(1) & 0xFF
        if key in (ord('q'), ord('Q')):
            break
        if key == ord(' '):
            if pending is None:
                print("  [!] No piece detected.")
                continue
            px, py, x_mm, y_mm = pending
            print(f"\n[Point {len(pixel_pts)+1}] camera -> ({x_mm:.1f}, {y_mm:.1f}) mm")
            joints = ask_joints()
            pixel_pts.append([px, py])
            robot_pts.append([x_mm, y_mm])
            joints_list.append(joints)
            print(f"  OK. Total: {len(pixel_pts)} points")

    cap.release()
    cv2.destroyAllWindows()

    if len(pixel_pts) < 4:
        print(f"\n[!] Only {len(pixel_pts)} points - need >= 4. Aborting.")
        return

    src = np.array(pixel_pts, dtype=np.float32)
    dst = np.array(robot_pts, dtype=np.float32)
    H, _ = cv2.findHomography(src, dst, cv2.RANSAC, 5.0)
    errors = [float(np.hypot(*(H @ np.array([px, py, 1.0]))[:2] /
                             (H @ np.array([px, py, 1.0]))[2] - np.array([rx, ry])))
              for (px, py), (rx, ry) in zip(pixel_pts, robot_pts)]
    print(f"\nReprojection error: max={max(errors):.2f}mm  mean={np.mean(errors):.2f}mm")

    np.save(str(HOMOGRAPHY_FILE), H)
    print("[OK] homography.npy updated")

    CALIB_FILE.write_text(json.dumps({
        "pixel_points": pixel_pts,
        "robot_mm_points": robot_pts,
        "joints": joints_list}, indent=2))
    print("[OK] calib_pairs.json updated")

    valid = [(rp, j) for rp, j in zip(robot_pts, joints_list) if j and len(j) == 6]
    if valid:
        build_pick_model([v[0] for v in valid], [v[1] for v in valid])
    else:
        print("  [!] No valid joints - pick_model.json not updated")


if __name__ == "__main__":
    main()
